#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App1.Resource", IsApplication=true)]

namespace App1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int back = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int color_toolbar = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int pink = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int white = 2130968578;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050005
			public const int margin_large = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int margin_medium = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int margin_small = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int padding_large = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int text_size_large = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int text_size_medium = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int text_size_small = 2131034114;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int android = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int brackets = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int eye = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int information = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int leftarrow = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int password = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int phonecall = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int splash = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int user = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000e
			public const int back = 2131230734;
			
			// aapt resource value: 0x7f080008
			public const int button1 = 2131230728;
			
			// aapt resource value: 0x7f080013
			public const int change_login = 2131230739;
			
			// aapt resource value: 0x7f08000d
			public const int change_register = 2131230733;
			
			// aapt resource value: 0x7f080004
			public const int editText1 = 2131230724;
			
			// aapt resource value: 0x7f080007
			public const int editText2 = 2131230727;
			
			// aapt resource value: 0x7f080012
			public const int editText3 = 2131230738;
			
			// aapt resource value: 0x7f080003
			public const int imageView1 = 2131230723;
			
			// aapt resource value: 0x7f080006
			public const int imageView2 = 2131230726;
			
			// aapt resource value: 0x7f080011
			public const int imageView3 = 2131230737;
			
			// aapt resource value: 0x7f080001
			public const int linearLayout1 = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int linearLayout2 = 2131230722;
			
			// aapt resource value: 0x7f080005
			public const int linearLayout3 = 2131230725;
			
			// aapt resource value: 0x7f08000a
			public const int linearLayout4 = 2131230730;
			
			// aapt resource value: 0x7f080010
			public const int linearLayout5 = 2131230736;
			
			// aapt resource value: 0x7f080009
			public const int textView1 = 2131230729;
			
			// aapt resource value: 0x7f08000f
			public const int textView2 = 2131230735;
			
			// aapt resource value: 0x7f080000
			public const int toolbar1 = 2131230720;
			
			// aapt resource value: 0x7f08000b
			public const int view1 = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int view2 = 2131230732;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Register = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f06000a
			public const int code = 2131099658;
			
			// aapt resource value: 0x7f060001
			public const int forgot_pw = 2131099649;
			
			// aapt resource value: 0x7f06000b
			public const int had_acc = 2131099659;
			
			// aapt resource value: 0x7f060002
			public const int login = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int login_lower = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int name = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int no_acc = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int password = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int phone = 2131099657;
			
			// aapt resource value: 0x7f060004
			public const int register = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int register_lower = 2131099653;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int MyTheme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int SplashTheme = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
