#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Exercise04.Resource", IsApplication=true)]

namespace Exercise04
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int black = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int gray = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int white = 2130968578;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050002
			public const int height_button = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int margin_medium = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int margin_small = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int padding_large = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int padding_medium = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int text_medium = 2131034117;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int backarrow = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070017
			public const int btn_0 = 2131165207;
			
			// aapt resource value: 0x7f070011
			public const int btn_1 = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int btn_2 = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int btn_3 = 2131165203;
			
			// aapt resource value: 0x7f07000c
			public const int btn_4 = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int btn_5 = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int btn_6 = 2131165198;
			
			// aapt resource value: 0x7f070007
			public const int btn_7 = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int btn_8 = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int btn_9 = 2131165193;
			
			// aapt resource value: 0x7f070014
			public const int btn_add = 2131165204;
			
			// aapt resource value: 0x7f070002
			public const int btn_c = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int btn_delete = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int btn_div = 2131165189;
			
			// aapt resource value: 0x7f070018
			public const int btn_dot = 2131165208;
			
			// aapt resource value: 0x7f07000a
			public const int btn_mul = 2131165194;
			
			// aapt resource value: 0x7f070004
			public const int btn_percent = 2131165188;
			
			// aapt resource value: 0x7f07000f
			public const int btn_sub = 2131165199;
			
			// aapt resource value: 0x7f070019
			public const int calculate = 2131165209;
			
			// aapt resource value: 0x7f070001
			public const int linearLayout1 = 2131165185;
			
			// aapt resource value: 0x7f070006
			public const int linearLayout2 = 2131165190;
			
			// aapt resource value: 0x7f07000b
			public const int linearLayout3 = 2131165195;
			
			// aapt resource value: 0x7f070010
			public const int linearLayout4 = 2131165200;
			
			// aapt resource value: 0x7f070015
			public const int linearLayout5 = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int linearLayout6 = 2131165206;
			
			// aapt resource value: 0x7f070000
			public const int result = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int btn_0 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int btn_1 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int btn_2 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int btn_3 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int btn_4 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int btn_5 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int btn_6 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int btn_7 = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int btn_8 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int btn_9 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int btn_addition = 2131099659;
			
			// aapt resource value: 0x7f060012
			public const int btn_c = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int btn_calculate = 2131099665;
			
			// aapt resource value: 0x7f06000e
			public const int btn_division = 2131099662;
			
			// aapt resource value: 0x7f060010
			public const int btn_dot = 2131099664;
			
			// aapt resource value: 0x7f06000d
			public const int btn_multiplication = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int btn_percent = 2131099663;
			
			// aapt resource value: 0x7f06000c
			public const int btn_subtraction = 2131099660;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
