#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Exercise05.Resource", IsApplication=true)]

namespace Exercise05
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070001
			public const int countries = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int states = 2131165184;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int light_skyblue = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050003
			public const int margin_small = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int text_size_large = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int text_size_medium = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int text_size_small = 2131034114;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int backarrow = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0001
			public const int button1 = 2131361793;
			
			// aapt resource value: 0x7f0a0016
			public const int country = 2131361814;
			
			// aapt resource value: 0x7f0a000b
			public const int editText1 = 2131361803;
			
			// aapt resource value: 0x7f0a000c
			public const int editText2 = 2131361804;
			
			// aapt resource value: 0x7f0a0010
			public const int editText3 = 2131361808;
			
			// aapt resource value: 0x7f0a0012
			public const int editText4 = 2131361810;
			
			// aapt resource value: 0x7f0a0015
			public const int editText5 = 2131361813;
			
			// aapt resource value: 0x7f0a0017
			public const int item1 = 2131361815;
			
			// aapt resource value: 0x7f0a0018
			public const int item2 = 2131361816;
			
			// aapt resource value: 0x7f0a0019
			public const int item3 = 2131361817;
			
			// aapt resource value: 0x7f0a0003
			public const int linearLayout1 = 2131361795;
			
			// aapt resource value: 0x7f0a0005
			public const int linearLayout2 = 2131361797;
			
			// aapt resource value: 0x7f0a0007
			public const int linearLayout3 = 2131361799;
			
			// aapt resource value: 0x7f0a0009
			public const int linearLayout4 = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public const int linearLayout5 = 2131361802;
			
			// aapt resource value: 0x7f0a000d
			public const int linearLayout6 = 2131361805;
			
			// aapt resource value: 0x7f0a000f
			public const int linearLayout7 = 2131361807;
			
			// aapt resource value: 0x7f0a0011
			public const int linearLayout8 = 2131361809;
			
			// aapt resource value: 0x7f0a0014
			public const int linearLayout9 = 2131361812;
			
			// aapt resource value: 0x7f0a0013
			public const int state = 2131361811;
			
			// aapt resource value: 0x7f0a0004
			public const int textView1 = 2131361796;
			
			// aapt resource value: 0x7f0a0006
			public const int textView2 = 2131361798;
			
			// aapt resource value: 0x7f0a0008
			public const int textView3 = 2131361800;
			
			// aapt resource value: 0x7f0a000e
			public const int textView4 = 2131361806;
			
			// aapt resource value: 0x7f0a0002
			public const int textView5 = 2131361794;
			
			// aapt resource value: 0x7f0a0000
			public const int toolbar = 2131361792;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int menu = 2131296256;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060008
			public const int address = 2131099656;
			
			// aapt resource value: 0x7f060001
			public const int app = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int city = 2131099657;
			
			// aapt resource value: 0x7f060004
			public const int connors = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int date = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int first_name = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int person_info = 2131099650;
			
			// aapt resource value: 0x7f060007
			public const int residence_address = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int social = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int zipcode = 2131099658;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int MyTheme = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
